
//In console
http :8080

//download httpie
//sudo snap install http    # version 2.4.0, or
// sudo snap install httpie  # version 3.2.2
//sudo apt  install httpie  # version 3.2.1-1


GET http://localhost:8080/api/content
